openapi: 3.0.0
info:
  description: >-
    The AutoRest service is a IoT backend service.
  version: "1.0.0-oas3"
  title: AutoRest-Service
  termsOfService: 'http://www.wk-music.de/'
  contact:
    email: info@wk-music.de
  license:
    name: Apache License 2.0
    url: 'http://www.apache.org/licenses/'
tags:
  - name: health
    description: readiness/healthcheck endpoints
paths:
  /health/health:
    servers:
      - url: 'https://autorest-srv/'
      - url: 'http://autorest-srv/'
    get:
      tags:
        - health
      summary: getting the actual health status of the service
      description: getting the actual health status of the service
      operationId: healthcheck
      responses:
        '200':
          description: service is healthy
        '503':
          description: service is unhealthy
  /health/readiness:
    servers:
      - url: 'https://autorest-srv/'
      - url: 'http://autorest-srv/'
    get:
     tags:
        - health
     summary: service is ready to get traffic
     description: ''
     operationId: readinesscheck
     responses:
        '200':
          description: service is ready
servers:
  - url: 'https://autorest-srv/'
  - url: 'http://autorest-srv/'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-es-apikey
      in: header