backendname: schematics
models:
    - name: schematic
      fields: 
        - name: Manufacturer
          type: string
          mandatory: true
          collection: false
        - name: Model
          type: string
          mandatory: true
          collection: false
        - name: Tags
          type: string
          mandatory: false
          collection: true
        - name: Files
          type: file
          mandatory: false
          collection: true
      indexes:
        - name: $fulltext
          fields:
            - Manufacturer
            - Model
            - Tags
        - name: Manufacturer
          fields:
            - Manufacturer
        - name: Tags
          fields:
            - Tags
