backendname: schematics
models:
    - name: schematic
      fields: 
        - name: Manufacturer
          type: string
          mandantory: true
          collection: false
        - name: Model
          type: string
          mandantory: true
          collection: false
        - name: Tags
          type: string
          mandantory: false
          collection: true
        - name: Files
          type: file
          mandantory: false
          collection: true
      indexes:
        - name: fulltext
          fields:
            - manufactuer
            - model
            - tags
        - name: manufacturer
          fields:
            - manufacturer
        - name: tags
          fields:
            - tags
