backendname: schematics
description: Willies World Schematics Database
models:
    - name: schematic
      fields: 
        - name: Manufacturer
          type: string
          mandatory: true
          collection: false
        - name: Model
          type: string
          mandatory: true
          collection: false
        - name: Tags
          type: string
          mandatory: false
          collection: true
        - name: Files
          type: file
          mandatory: false
          collection: true
      indexes:
        - name: $fulltext
          fields:
            - Manufacturer
            - Model
            - Tags
        - name: Foreignid
          unique: true
          fields:
            - Foreignid
    - name: manufacturers
      fields: 
        - name: name
          type: string
          mandatory: true
          collection: false
      indexes:
        - name: name
          unique: true
          fields:
            - name
    - name: tags
      fields: 
        - name: name
          type: string
          mandatory: true
          collection: false
      indexes:
        - name: name
          unique: true
          fields:
            - name
