backendname: mybe
models:
  - name: mymodel
    fields:
      - name: title
        type: string
        mandantory: true
        collection: false
      - name: tags
        type: string
        mandantory: false
        collection: true
      - name: file
        type: file
        mandantory: false
        collection: false
    indexes:
      - name: $fulltext
        fields:
          - title
          - tags
      - name: title
        fields:
          - title
      - name: tags
        fields:
          - tags