# port of the http server
port: 9080 
# port of the https server
sslport: 9443
# this is the servicURL from outside
serviceURL: https://127.0.0.1:9443
# this is the registry URL from inside
registryURL: 
# this is the system id of this service. services in a cluster mode should have the same system id.
systemID: autorest-srv
#sercret file for storing usernames and passwords
secretfile: configs/secret.yaml
#where the configuration of the backends are
backendpath: configs/backends
#allow data saving without a registered backend
allowAnonymousBackend: true
webRoot: ../autorestui/dist

logging:
    gelf-url: 
    gelf-port: 

healthcheck:
    period: 30

backgroundtasks:
    period: 86400
    deleteOrphanedFiles: true

mongodb:
    host: 192.168.178.14
    port: 27017
    username:
    password:
    authdb: backend1
    database: backend1
